### ISSUE TITLE
请问能否告知数据集文件夹的具体层次格式

### ISSUE THREAD

**Issue by lbwang1234** [Spritea/Context-Aggregation-Network#1]
I'm a beginner of semantic segmentation, and attacted by your paper.
when i run train.py i meet a problem, it is
File"/path/ptsemseg/models/__init__.py",line 46,in get_model
     model = model(n_classes, **param_dict)
TypeError: CAN50( ) missing 1 required positional argument: 'num_classes'
how can i fix it?Could you give me some advise?
thanks

**Comment by lbwang1234** [comment]
还有这个validation是怎么用的呢？=_=

**Comment by Spritea** [comment]
Hi~
It seems that the problem is you did not create an applicable dataset. The dataset foulder should have the following structure:

    ├── "dataset_name"                   
    |   ├── train
    |   ├── train_labels
    |   ├── val
    |   ├── val_labels
    |   ├── test
    |   ├── test_labels

The value of `num_classes` is set in the dataloader function here: https://github.com/Spritea/Context-Aggregation-Network/blob/master/ptsemseg/loader/my_loader.py#L35.
So after you create the right dataset folder and use `my_loader.py` as the dataloader function, it should be solved.

**Comment by twsha** [comment]
你好，请问你那有本开源项目的处理好的数据集吗

**Comment by Spritea** [comment]
> Hi~ It seems that the problem is you did not create an applicable dataset. The dataset foulder should have the following structure:
> 
> ```
> ├── "dataset_name"                   
> |   ├── train
> |   ├── train_labels
> |   ├── val
> |   ├── val_labels
> |   ├── test
> |   ├── test_labels
> ```
> 
> The value of `num_classes` is set in the dataloader function here: https://github.com/Spritea/Context-Aggregation-Network/blob/master/ptsemseg/loader/my_loader.py#L35. So after you create the right dataset folder and use `my_loader.py` as the dataloader function, it should be solved.

Looks like the official page is missing. Unfortunately I don't have the data by hand. Maybe they will fix the link later.
